// +build !ignore_autogenerated_etcd_cluster

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	apiv1alpha3 "github.com/mrajashree/etcdadm-bootstrap-provider/api/v1alpha3"
	v1beta1 "github.com/mrajashree/etcdadm-controller/api/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterapiapiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*EtcdadmCluster)(nil), (*v1beta1.EtcdadmCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster(a.(*EtcdadmCluster), b.(*v1beta1.EtcdadmCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EtcdadmCluster)(nil), (*EtcdadmCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster(a.(*v1beta1.EtcdadmCluster), b.(*EtcdadmCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdadmClusterList)(nil), (*v1beta1.EtcdadmClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EtcdadmClusterList_To_v1beta1_EtcdadmClusterList(a.(*EtcdadmClusterList), b.(*v1beta1.EtcdadmClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EtcdadmClusterList)(nil), (*EtcdadmClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdadmClusterList_To_v1alpha3_EtcdadmClusterList(a.(*v1beta1.EtcdadmClusterList), b.(*EtcdadmClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdadmClusterSpec)(nil), (*v1beta1.EtcdadmClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec(a.(*EtcdadmClusterSpec), b.(*v1beta1.EtcdadmClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EtcdadmClusterSpec)(nil), (*EtcdadmClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec(a.(*v1beta1.EtcdadmClusterSpec), b.(*EtcdadmClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdadmClusterStatus)(nil), (*v1beta1.EtcdadmClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus(a.(*EtcdadmClusterStatus), b.(*v1beta1.EtcdadmClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EtcdadmClusterStatus)(nil), (*EtcdadmClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus(a.(*v1beta1.EtcdadmClusterStatus), b.(*EtcdadmClusterStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster(in *EtcdadmCluster, out *v1beta1.EtcdadmCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster is an autogenerated conversion function.
func Convert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster(in *EtcdadmCluster, out *v1beta1.EtcdadmCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster(in, out, s)
}

func autoConvert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster(in *v1beta1.EtcdadmCluster, out *EtcdadmCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster is an autogenerated conversion function.
func Convert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster(in *v1beta1.EtcdadmCluster, out *EtcdadmCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster(in, out, s)
}

func autoConvert_v1alpha3_EtcdadmClusterList_To_v1beta1_EtcdadmClusterList(in *EtcdadmClusterList, out *v1beta1.EtcdadmClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.EtcdadmCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_EtcdadmCluster_To_v1beta1_EtcdadmCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_EtcdadmClusterList_To_v1beta1_EtcdadmClusterList is an autogenerated conversion function.
func Convert_v1alpha3_EtcdadmClusterList_To_v1beta1_EtcdadmClusterList(in *EtcdadmClusterList, out *v1beta1.EtcdadmClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_EtcdadmClusterList_To_v1beta1_EtcdadmClusterList(in, out, s)
}

func autoConvert_v1beta1_EtcdadmClusterList_To_v1alpha3_EtcdadmClusterList(in *v1beta1.EtcdadmClusterList, out *EtcdadmClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdadmCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_EtcdadmCluster_To_v1alpha3_EtcdadmCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_EtcdadmClusterList_To_v1alpha3_EtcdadmClusterList is an autogenerated conversion function.
func Convert_v1beta1_EtcdadmClusterList_To_v1alpha3_EtcdadmClusterList(in *v1beta1.EtcdadmClusterList, out *EtcdadmClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdadmClusterList_To_v1alpha3_EtcdadmClusterList(in, out, s)
}

func autoConvert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec(in *EtcdadmClusterSpec, out *v1beta1.EtcdadmClusterSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.InfrastructureTemplate = in.InfrastructureTemplate
	if err := apiv1alpha3.Convert_v1alpha3_EtcdadmConfigSpec_To_v1beta1_EtcdadmConfigSpec(&in.EtcdadmConfigSpec, &out.EtcdadmConfigSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec(in *EtcdadmClusterSpec, out *v1beta1.EtcdadmClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_EtcdadmClusterSpec_To_v1beta1_EtcdadmClusterSpec(in, out, s)
}

func autoConvert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec(in *v1beta1.EtcdadmClusterSpec, out *EtcdadmClusterSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.InfrastructureTemplate = in.InfrastructureTemplate
	if err := apiv1alpha3.Convert_v1beta1_EtcdadmConfigSpec_To_v1alpha3_EtcdadmConfigSpec(&in.EtcdadmConfigSpec, &out.EtcdadmConfigSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec(in *v1beta1.EtcdadmClusterSpec, out *EtcdadmClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdadmClusterSpec_To_v1alpha3_EtcdadmClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus(in *EtcdadmClusterStatus, out *v1beta1.EtcdadmClusterStatus, s conversion.Scope) error {
	out.ReadyReplicas = in.ReadyReplicas
	out.InitMachineAddress = in.InitMachineAddress
	out.Initialized = in.Initialized
	out.Ready = in.Ready
	out.CreationComplete = in.CreationComplete
	out.Endpoints = in.Endpoints
	out.Selector = in.Selector
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus(in *EtcdadmClusterStatus, out *v1beta1.EtcdadmClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_EtcdadmClusterStatus_To_v1beta1_EtcdadmClusterStatus(in, out, s)
}

func autoConvert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus(in *v1beta1.EtcdadmClusterStatus, out *EtcdadmClusterStatus, s conversion.Scope) error {
	out.ReadyReplicas = in.ReadyReplicas
	out.InitMachineAddress = in.InitMachineAddress
	out.Initialized = in.Initialized
	out.Ready = in.Ready
	out.CreationComplete = in.CreationComplete
	out.Endpoints = in.Endpoints
	out.Selector = in.Selector
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*clusterapiapiv1alpha3.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus(in *v1beta1.EtcdadmClusterStatus, out *EtcdadmClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_EtcdadmClusterStatus_To_v1alpha3_EtcdadmClusterStatus(in, out, s)
}
